enum Goods {
  WHEAT = '🌾',
  SILK_FABRICS = '👗',
  STEEL = '⛓',
  SPICES = '🫚',
  FLURORIT = '🧪',
  ALKARKOTICA = '🧿',
  SEN_ROOT = '🦪',
  DAMAST = '🍥',
  SILICIUM = '💠',
  PLATINUM_WOOD = '🪵',
  ELEMENT_ZERO = '🔋',
  GRAVIUM = '🪽',
  KRYPTONIT = '🩸',
  UNOPTANIUM = '🧲',
  ZRBIT = '🦠',
  BAVARIUM = '💣',
  PHAZON = '🧪',
  AETHER = '🌡',
  DILITHIUM = '💎',
}

type Product = {
  icon: string;
  name: Record<string, string>;
  price: {
    min: number;
    max: number;
    demand: 1 | 1.5 | 2 | 2.5 | 3;
  };
};

export const PRODUCTS: Product[] = [
  {
    icon: Goods.WHEAT,
    name: {
      en: 'Wheat',
      de: 'Weizen',
      fr: 'Blé',
      it: 'Grano',
      sp: 'Trigo',
      ru: 'Пшеница',
      jp: '小麦',
      cn: '小麦',
      in: 'गह',
    },
    price: {
      min: 1,
      max: 4,
      demand: 1,
    },
  },
  {
    icon: Goods.SILK_FABRICS,
    name: {
      en: 'Silk Fabrics',
      de: 'Seidenstoffe',
      fr: 'Tissus de soie',
      it: 'Tessuti di seta',
      sp: 'Tejidos de seda',
      ru: 'Шелковые ткани',
      jp: '絹織物',
      cn: '丝绸织物',
      in: 'रशम क कपड',
    },
    price: {
      min: 10,
      max: 50,
      demand: 2,
    },
  },
  {
    icon: Goods.STEEL,
    name: {
      en: 'Steel',
      de: 'Stahl',
      fr: 'Acier',
      it: 'Acciaio',
      sp: 'Acero',
      ru: 'Сталь',
      jp: '鋼鉄',
      cn: '钢',
      in: 'इसपत',
    },
    price: {
      min: 20,
      max: 80,
      demand: 2.5,
    },
  },
  {
    icon: Goods.SPICES,
    name: {
      en: 'Spices',
      de: 'Gewürze',
      fr: 'Épices',
      it: 'Spezie',
      sp: 'Especias',
      ru: 'Специи',
      jp: '香辛料',
      cn: '香料',
      in: 'मसल',
    },
    price: {
      min: 5,
      max: 25,
      demand: 1.5,
    },
  },
  {
    icon: Goods.FLURORIT,
    name: {
      en: 'Fluorite',
      de: 'Fluorit',
      fr: 'Fluorite',
      it: 'Fluorite',
      sp: 'Fluorita',
      ru: 'Флюорит',
      jp: '蛍石',
      cn: '萤石',
      in: 'फलरट',
    },
    price: {
      min: 15,
      max: 45,
      demand: 2,
    },
  },
  {
    icon: Goods.ALKARKOTICA,
    name: {
      en: 'Alkarkotica',
      de: 'Alkarkotika',
      fr: 'Alkarkotica',
      it: 'Alkarkotica',
      sp: 'Alkarkotica',
      ru: 'Алкаркотика',
      jp: 'アルカコティカ',
      cn: '阿尔卡科蒂卡',
      in: 'अलकरकटक',
    },
    price: {
      min: 50,
      max: 150,
      demand: 3,
    },
  },
  {
    icon: Goods.SEN_ROOT,
    name: {
      en: 'Sen Root',
      de: 'Senwurzel',
      fr: 'Racine de Sen',
      it: 'Radice di Sen',
      sp: 'Raíz de Sen',
      ru: 'Корень Сен',
      jp: 'センの根',
      cn: '森根',
      in: 'सन रट',
    },
    price: {
      min: 10,
      max: 30,
      demand: 1.5,
    },
  },
  {
    icon: Goods.DAMAST,
    name: {
      en: 'Damask',
      de: 'Damast',
      fr: 'Damas',
      it: 'Damasco',
      sp: 'Damasco',
      ru: 'Дамаск',
      jp: 'ダマスク',
      cn: '大马士革',
      in: 'डमसक',
    },
    price: {
      min: 30,
      max: 90,
      demand: 2.5,
    },
  },
  {
    icon: Goods.SILICIUM,
    name: {
      en: 'Silicium',
      de: 'Silicium',
      fr: 'Silicium',
      it: 'Silicio',
      sp: 'Silicio',
      ru: 'Силициум',
      jp: 'シリシウム',
      cn: '硅',
      in: 'सलकयम',
    },
    price: {
      min: 20,
      max: 60,
      demand: 2,
    },
  },
  {
    icon: Goods.PLATINUM_WOOD,
    name: {
      en: 'Platinum Wood',
      de: 'Platinholz',
      fr: 'Bois de platine',
      it: 'Legno di platino',
      sp: 'Madera de platino',
      ru: 'Платиновое дерево',
      jp: 'プラチナウッド',
      cn: '铂木',
      in: 'पलटनम वड',
    },
    price: {
      min: 100,
      max: 300,
      demand: 3,
    },
  },
  {
    icon: Goods.ELEMENT_ZERO,
    name: {
      en: 'Element Zero',
      de: 'Element Null',
      fr: 'Élément Zéro',
      it: 'Elemento Zero',
      sp: 'Elemento Cero',
      ru: 'Элемент Ноль',
      jp: 'エレメントゼロ',
      cn: '零元素',
      in: 'ततव शनय',
    },
    price: {
      min: 200,
      max: 500,
      demand: 3,
    },
  },
  {
    icon: Goods.GRAVIUM,
    name: {
      en: 'Gravium',
      de: 'Gravium',
      fr: 'Gravium',
      it: 'Gravio',
      sp: 'Gravio',
      ru: 'Гравиум',
      jp: 'グラビウム',
      cn: '重力素',
      in: 'गरवयम',
    },
    price: {
      min: 150,
      max: 450,
      demand: 2.5,
    },
  },
  {
    icon: Goods.KRYPTONIT,
    name: {
      en: 'Kryptonite',
      de: 'Kryptonit',
      fr: 'Kryptonite',
      it: 'Krypton',
      sp: 'Kryptonita',
      ru: 'Криптонит',
      jp: 'クリプトナイト',
      cn: '氪石',
      in: 'करपटनइट',
    },
    price: {
      min: 80,
      max: 240,
      demand: 2,
    },
  },
  {
    icon: Goods.UNOPTANIUM,
    name: {
      en: 'Unoptanium',
      de: 'Unoptanium',
      fr: 'Unoptanium',
      it: 'Unoptanio',
      sp: 'Unoptanio',
      ru: 'Уноптаниум',
      jp: 'ウノプタニウム',
      cn: '不可获得素',
      in: 'अनऑपटनयम',
    },
    price: {
      min: 120,
      max: 360,
      demand: 2.5,
    },
  },
  {
    icon: Goods.ZRBIT,
    name: {
      en: 'Zrbit',
      de: 'Zrbit',
      fr: 'Zrbit',
      it: 'Zrbit',
      sp: 'Zrbit',
      ru: 'Зрбит',
      jp: 'ズルビット',
      cn: '锆素',
      in: 'जरबट',
    },
    price: {
      min: 70,
      max: 210,
      demand: 1.5,
    },
  },
  {
    icon: Goods.BAVARIUM,
    name: {
      en: 'Bavarium',
      de: 'Bavarium',
      fr: 'Bavarium',
      it: 'Bavario',
      sp: 'Bavarium',
      ru: 'Бавариум',
      jp: 'ババリウム',
      cn: '巴瓦里姆',
      in: 'बवरयम',
    },
    price: {
      min: 90,
      max: 270,
      demand: 2,
    },
  },
  {
    icon: Goods.PHAZON,
    name: {
      en: 'Phazon',
      de: 'Phazon',
      fr: 'Phazon',
      it: 'Phazon',
      sp: 'Phazon',
      ru: 'Фазон',
      jp: 'フェイゾン',
      cn: '相位素',
      in: 'फजन',
    },
    price: {
      min: 110,
      max: 330,
      demand: 2.5,
    },
  },
  {
    icon: Goods.AETHER,
    name: {
      en: 'Aether',
      de: 'Äther',
      fr: 'Éther',
      it: 'Etere',
      sp: 'Éter',
      ru: 'Эфир',
      jp: 'エーテル',
      cn: '以太',
      in: 'ईथर',
    },
    price: {
      min: 130,
      max: 390,
      demand: 2.5,
    },
  },
  {
    icon: Goods.DILITHIUM,
    name: {
      en: 'Dilithium',
      de: 'Dilithium',
      fr: 'Dilithium',
      it: 'Dilitio',
      sp: 'Dilitio',
      ru: 'Дилитиум',
      jp: 'デュリチウム',
      cn: '双锂',
      in: 'डलथयम',
    },
    price: {
      min: 160,
      max: 480,
      demand: 3,
    },
  },
];
